# Generated by Django 4.0.6 on 2022-08-05 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ads_brand_slider_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField(default=0)),
                ('discont_price', models.IntegerField(default=0)),
                ('stock', models.CharField(choices=[('In', 'In Stock'), ('Out', 'Out stock')], max_length=20)),
                ('lables', models.CharField(blank=True, choices=[('hot', 'hot'), ('sale', 'sale'), ('new', 'new'), ('', 'defult')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
            ],
        ),
    ]
