# Generated by Django 4.0.6 on 2022-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowerads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('remark', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('rank', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='remark',
            field=models.CharField(max_length=500),
        ),
    ]
