# Generated by Django 4.0.6 on 2022-08-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lowerads_service_alter_review_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lowerads',
        ),
        migrations.AlterField(
            model_name='ads',
            name='rank',
            field=models.ImageField(upload_to=''),
        ),
    ]
